[versions]
kotlin-logging = "7.0.14"
logback-classic = "1.5.24"

[libraries]
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic" }

[bundles]
logging = ["kotlin-logging", "logback-classic"]

[plugins]
